version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_demo
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - POSTGRES_DB=demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo_network

volumes:
  postgres_data:

networks:
  demo_network:
    driver: bridge
